services:
    simple-api:
        # Repertoire où se situe le DockerFile
        build: ./simple-api-student-main
        # Network du service
        networks: 
            - back-network
            - front-network
        env_file: "/simple-api-student-main/.env"
        # Dépendant du container        
        depends_on: 
            - db

    db:
        build: ./Database
        env_file: "/Database/.env"
        networks:
            - back-network
    
    front:
        build: ./front/devops-front-main
        ports:
            - "80:80"
        networks:
            - front-network

    httpd:
        build: ./HttpServer
        # Exposé sur le port
        ports: 
            - "8080:8080"
        networks: 
            - front-network
        depends_on: 
            - simple-api
            - front
    
# Network existants
networks:
    front-network:
    back-network:
    
