name: CI devops 2025
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: 
      - main
      - staging
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout
        uses: actions/checkout@v4
            
      #do the same with another action (actions/setup-java@v3) that enable to setup jdk 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with: 
          java-version: '21'
          distribution: 'corretto'

      #finally build your app with the latest command
      - name: Build and test with Maven
        # execute all the tests et vérifie la qualité du code avec sonar cube (connexion et vérification grâce aux infos dans les secrets [project_key, etc])
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=${{secrets.PROJECT_KEY}} -Dsonar.organization=${{secrets.ORGANISATION_KEY}} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml
        working-directory: TP1/simple-api-student-main